#!/bin/sh /etc/rc.common

USE_PROCD=1

START=95
STOP=01

PROG=/usr/sbin/sipserver

start_service() {
	. /lib/functions/network.sh
	network_get_ipaddr ip "lan"

	procd_open_instance

	procd_set_param command "$PROG"
	procd_append_param command --ip "$ip"
	procd_append_param command --port 5060

	procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-5} ${respawn_retry:-5}

	procd_set_param stdout 1
	procd_set_param stderr 1

	procd_close_instance
}
