name: Build

on:
  # push:
  #   paths:
  #     - '**/Makefile'
  # pull_request:
  #   branches:
  #     - main
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug

jobs:
  build:
    name: ${{ matrix.arch }} build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          # - x86_64
          - mips_24kc
          # - arm_cortex-a7_neon-vfpv4

    steps:
      - uses: actions/checkout@v4

      - name: Build
        uses: openwrt/gh-action-sdk@main
        env:
          ARCH: ${{ matrix.arch }}
          PACKAGES: phonebook sipserver
          V: sc

      - name: Store packages
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.arch}}-packages
          path: bin/packages/${{ matrix.arch }}/*.ipk
