name: Build packages

on:
  release:
    types: [created]
  # pull_request:
  #   branches: [main]
  #   types: [opened]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'info'
        type: choice
        options:
        - info
        - warning
        - debug

jobs:
  build:
    name: Build ${{ matrix.arch }} ${{ github.ref }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        arch:
          - x86_64
          - mips_24kc
          - arm_cortex-a7_neon-vfpv4

    steps:
      - name: Install UPX Packer
        run: |
          sudo apt-get install -y upx-ucl

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        uses: openwrt/gh-action-sdk@main
        env:
          ARCH: ${{ matrix.arch }}
          FEEDNAME: aredn
          PACKAGES: phonebook sipserver
          V: sc

      - name: Move created packages to project dir
        run: |
          cp bin/packages/${{ matrix.arch }}/aredn/*.ipk . || true
          cp bin/targets/*/*/packages/libstdcpp6*.ipk . || true

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.arch }}-packages
          path: |
            *.ipk

      - name: Create release ZIP
        run: |
          zip ${{ matrix.arch }}.zip *.ipk

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: ${{ github.event.release.tag_name }}
          tag_name: ${{ github.event.release.tag_name }}
          body: ${{ github.event.release.body }}
          prerelease: ${{ github.event.release.prerelease }}
          draft: ${{ github.event.release.draft }}
          files: |
            ${{ matrix.arch }}.zip