name: Build packages

on:
  release:
    types: [created]
  pull_request:
    branches: [main]
    types: [opened]
  push:
    branches: [main]
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug

jobs:
  build:
    name: Build ${{ matrix.arch }} ${{ github.ref }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - x86_64
          - mips_24kc
          - arm_cortex-a7_neon-vfpv4

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        uses: openwrt/gh-action-sdk@main
        env:
          ARCH: ${{ matrix.arch }}
          FEEDNAME: aredn
          PACKAGES: phonebook sipserver
          V: sc

      - name: Move created packages to project dir
        run: |
          cp bin/packages/${{ matrix.arch }}/aredn/*.ipk . || true
          cp bin/targets/*/*/packages/libstdcpp6*.ipk . || true

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.arch}}-packages
          path: |
            *.ipk

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          prerelease: true
          draft: true
          files: |
            *.ipk