name: Build packages

on:
  release:
    types: [created]
  # pull_request:
  #   branches: [main]
  #   types: [opened]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'info'
        type: choice
        options:
        - info
        - warning
        - debug

jobs:
  build:
    name: Build ${{ matrix.arch }} ${{ github.ref }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        openwrt:
          - main          # APK packages going forward
          - openwrt-24.10 # IPK packages built using an older version
        arch:
          - x86_64
          - mips_24kc
          - arm_cortex-a7_neon-vfpv4

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        uses: openwrt/gh-action-sdk@main
        env:
          ARCH: ${{ matrix.arch }}-${{ matrix.openwrt }}
          FEEDNAME: aredn
          EXTRA_FEEDS: "src-git|upx|https://github.com/kuoruan/openwrt-upx.git"
          PACKAGES: phonebook
          V: sc

      - name: Move created packages to project dir
        if: ${{ matrix.openwrt != 'main' }}
        run: |
          cp bin/packages/${{ matrix.arch }}/aredn/phonebook*.ipk . || true
          cp bin/packages/${{ matrix.arch }}/aredn/phonebook*.apk . || true

      - name: Upload APK artifacts
        if: ${{ github.ref_name == 'main' }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.arch }}-apk
          compression-level: 0 # no compression
          path: |
            *.apk

      - name: Upload IPK artifacts
        if: ${{ github.ref_name != 'main' }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.arch }}-ipk
          compression-level: 0 # no compression
          path: |
            *.ipk

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: ${{ github.event.release.tag_name }}
          tag_name: ${{ github.event.release.tag_name }}
          body: ${{ github.event.release.body }}
          prerelease: ${{ github.event.release.prerelease }}
          draft: ${{ github.event.release.draft }}
          files: |
            *.ipk
            *.apk
